class_name PointTextures
extends Resource

var textures: Array[PointTextureData] = [
	PointTextureData.new("res://assets/tree/point_textures/empty.svg", "Empty"),
	# Stats
	PointTextureData.new("res://assets/tree/point_textures/red.png", "Red"),
	PointTextureData.new("res://assets/tree/point_textures/green.png", "Green"),
	PointTextureData.new("res://assets/tree/point_textures/blue.png", "Blue"),
	PointTextureData.new("res://assets/tree/point_textures/purple.png", "Purple"),
	# Points
	PointTextureData.new("res://assets/tree/point_textures/Life.png", "Life"),
	PointTextureData.new("res://assets/tree/point_textures/Mana.png", "Mana"),
	PointTextureData.new("res://assets/tree/point_textures/Armour.png", "Armour"),
	PointTextureData.new("res://assets/tree/point_textures/LifeAndMana.png", "LifeAndMana"),
	PointTextureData.new("res://assets/tree/point_textures/Cold.png", "Cold"),
	PointTextureData.new("res://assets/tree/point_textures/Fire.png", "Fire"),
	PointTextureData.new("res://assets/tree/point_textures/Lightning.png", "Lightning"),
	PointTextureData.new("res://assets/tree/point_textures/Chaos.png", "Chaos"),
	PointTextureData.new("res://assets/tree/point_textures/Magic.png", "Magic"),
	PointTextureData.new("res://assets/tree/point_textures/CastSpeed.png", "CastSpeed"),
	PointTextureData.new("res://assets/tree/point_textures/Attack.png", "Attack"),
	PointTextureData.new("res://assets/tree/point_textures/2HandAxe.png", "2HandAxe"),
	PointTextureData.new("res://assets/tree/point_textures/1HandAxe.png", "1HandAxe"),
	PointTextureData.new("res://assets/tree/point_textures/Shield.png", "Shield"),
	PointTextureData.new("res://assets/tree/point_textures/Dagger.png", "Dagger"),
	PointTextureData.new("res://assets/tree/point_textures/Staff.png", "Staff"),
	PointTextureData.new("res://assets/tree/point_textures/Crit.png", "Crit"),
	PointTextureData.new("res://assets/tree/point_textures/Blood.png", "Blood"),
	PointTextureData.new("res://assets/tree/point_textures/DamageOverTime.png", "DamageOverTime"),
	PointTextureData.new("res://assets/tree/point_textures/MovementSpeed.png", "MovementSpeed"),
	PointTextureData.new("res://assets/tree/point_textures/AttackSpeed.png", "AttackSpeed"),
	# Notables
	PointTextureData.new("res://assets/tree/point_textures/ManaShield.png", "ManaShield"),
	PointTextureData.new("res://assets/tree/point_textures/Dodge.png", "Dodge"),
	# Movement
	PointTextureData.new("res://assets/tree/point_textures/Dash.png", "Dash"),
	PointTextureData.new("res://assets/tree/point_textures/Teleport.png", "Teleport"),
	PointTextureData.new("res://assets/tree/point_textures/Jump.png", "Jump"),
	PointTextureData.new("res://assets/tree/point_textures/ShadowWalk.png", "ShadowWalk"),
	# Skills
	PointTextureData.new("res://assets/tree/point_textures/RainOfFire.png", "RainOfFire"),
	PointTextureData.new("res://assets/tree/point_textures/ChaosAura.png", "ChaosAura"),
	PointTextureData.new("res://assets/tree/point_textures/AxeWind.png", "AxeWind"),
	PointTextureData.new("res://assets/tree/point_textures/BleedingDaggers.png", "BleedingDaggers"),
]
