class_name Rule

enum RULE {
	DAMAGE_TAKEN_AS_MANA = 1,
	YOUR_ARMOUR_IS_0 = 2,
	CHAOS_CAN_IGNITE = 3,
	YOUR_ATTACKS_CAN_IGNITE = 4,
	YOUR_ATTACKS_CAN_CHILL = 5,
	YOUR_ATTACKS_CAN_SHOCK = 6,
	MAGIC_DAMAGE_TAKEN_AS_CHAOS = 7,
	CHAOS_TAKEN_AS_MAGIC = 8,
	LIFE_ON_HIT = 9,
	MANA_ON_HIT = 10,
  YOUR_DODGE_IS_CAPPED_AT = 11,
  RECOVER_MANA_ON_DODGE = 12,
  RECOVER_LIFE_ON_DODGE = 12,
}
